# Generated by Django 6.0.3 on 2026-04-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('Claimable', 'Claimable'), ('Non-Claimable', 'Non-Claimable')], max_length=20)),
                ('travel_type', models.CharField(choices=[('Office', 'Office'), ('Client Visit', 'Client Visit')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('expense', models.CharField(max_length=100)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('conversion_rate', models.FloatField(default=1.0)),
                ('unit_value', models.FloatField()),
                ('amount', models.FloatField()),
                ('final_amount', models.FloatField()),
                ('project', models.CharField(max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('bill', models.FileField(blank=True, null=True, upload_to='bills/')),
                ('remarks', models.TextField()),
            ],
        ),
    ]
