# Generated by Django 6.0.3 on 2026-04-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='project',
            field=models.CharField(default='Office', max_length=100),
        ),
    ]
