# Generated by Django 6.0.3 on 2026-04-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_application', '0002_alter_expense_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='city',
            field=models.CharField(default='Mumbai', max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense',
            field=models.CharField(choices=[('Traveling Expenses', 'Traveling Expenses'), ('Food Expense', 'Food Expense'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='project',
            field=models.CharField(choices=[('Full Stack Web Development', 'Full Stack Web Development'), ('Other', 'Other')], max_length=100),
        ),
    ]
