# Generated by Django 6.0.3 on 2026-04-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_application', '0003_expense_status_alter_expense_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
