# Generated by Django 6.0.3 on 2026-04-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_application', '0004_alter_expense_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='unit_value',
        ),
    ]
