# Generated by Django 5.0.6 on 2025-07-06 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(default='January, 2025 - December, 2025', max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('start_day', models.CharField(choices=[('Full', 'Full Day'), ('Half', 'Half Day')], max_length=10)),
                ('end_day', models.CharField(choices=[('Full', 'Full Day'), ('Half', 'Half Day')], max_length=10)),
                ('half_start', models.CharField(blank=True, choices=[('First', 'First Half'), ('Second', 'Second Half')], max_length=10, null=True)),
                ('half_end', models.CharField(blank=True, choices=[('First', 'First Half'), ('Second', 'Second Half')], max_length=10, null=True)),
                ('leave_type', models.CharField(choices=[('PL', 'Privilege Leave'), ('CL', 'Casual Leave'), ('SL', 'Sick Leave')], max_length=5)),
                ('total_days', models.FloatField(default=1)),
                ('reason', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='leave_docs/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
