# Generated by Django 5.0.6 on 2025-07-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='end_day',
            field=models.CharField(choices=[('Full', 'Full'), ('Half', 'Half')], max_length=10),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='period',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='start_day',
            field=models.CharField(choices=[('Full', 'Full'), ('Half', 'Half')], max_length=10),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='total_days',
            field=models.FloatField(),
        ),
    ]
