# Generated by Django 5.0.6 on 2025-07-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_application', '0002_leaveapplication_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='half_end',
            field=models.CharField(choices=[('First', 'First Half'), ('Second', 'Second Half')], default='nill', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='half_start',
            field=models.CharField(choices=[('First', 'First Half'), ('Second', 'Second Half')], default='kunal', max_length=10),
            preserve_default=False,
        ),
    ]
