# Generated by Django 6.0.3 on 2026-04-02 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swipe_application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swipeapplication',
            name='inout_mode',
        ),
        migrations.AlterField(
            model_name='swipeapplication',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_swipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='swipeapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_swipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
