# Generated by Django 6.0.3 on 2026-04-11 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swipe_application', '0002_remove_swipeapplication_inout_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='swipeapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_swipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
