# Generated by Django 6.0.3 on 2026-04-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
